// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Project_.Persistence;

#nullable disable

namespace _Project_.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923113020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("_Project_.Domain.Entities.ExampleAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExampleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("_Project_.Domain.Entities.ExampleItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExampleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId");

                    b.ToTable("ExampleItems");
                });

            modelBuilder.Entity("_Project_.Domain.Entities.ExampleAggregate", b =>
                {
                    b.OwnsOne("_Project_.Domain.ValueObjects.ExampleValueObject", "ExampleValueObject", b1 =>
                        {
                            b1.Property<Guid>("ExampleAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExampleValue")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.HasKey("ExampleAggregateId");

                            b1.ToTable("Examples");

                            b1.WithOwner()
                                .HasForeignKey("ExampleAggregateId");
                        });

                    b.Navigation("ExampleValueObject")
                        .IsRequired();
                });

            modelBuilder.Entity("_Project_.Domain.Entities.ExampleItemEntity", b =>
                {
                    b.HasOne("_Project_.Domain.Entities.ExampleAggregate", "Example")
                        .WithMany("Items")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");
                });

            modelBuilder.Entity("_Project_.Domain.Entities.ExampleAggregate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
